name: Security leaks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  actions: read

jobs:
  find-secrets:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@59fdd904af445f5a90568b4931a6e7e6a2aa5cb2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
